# RENAMING FILE NAMES FROM NUM TO THEIR ACTUAL CHAR NAME

Initially the dataset we had were not named according to their character name but were assigned a number corresponding to the character name.

<b>For example,</b> directory with name 1 inside directory vowels corresponds to character 'a'.

To make programming easier, renaming of directory to their actual character name is done.

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dir = os.path.join(os.getcwd(),'Dataset')

In [4]:
for x in os.listdir(dir):
    newdir=os.path.join(dir,x)
    #print(x)
    for nx in os.listdir(newdir):
        print(nx)

aa
ah
o
an
u
a
ai
oo
i
ae
au
ee
tra
gha
cha
la
kna
petchiryosaw
ha
tha
va
chha
dhaa
dha
ja
thaa
ma
pa
ana
ksha
jha
patalosaw
ka
ta
ya
gya
ba
pha
ra
daa
kha
motosaw
ga
na
bha
da
yna
taa
3
8
6
4
1
9
0
2
7
5

In [2]:
df = pd.read_csv('labels.csv')
df

   Numerals Unnamed: 1        Unnamed: 2 Unnamed: 3
0       NaN        NaN               NaN        NaN
1     Class      Label  Devanagari Label  Phonetics
2         0          0                 ०     Śūn'ya
3         1          1                 १        ēka
4         2          2                 २       du'ī
..      ...        ...               ...        ...
65       32  patalosaw                 स         sa
66       33         ha                 ह         ha
67       34       ksha               क्ष        kṣa
68       35        tra               त्र        tra
69       36        gya               ज्ञ        jña

[70 rows x 4 columns]

In [5]:
#Since the column names contain spaces, we rename the columns to avoid further problems
df.columns=['class_','label','devnagrilabel','phonetics']
df

   class_      label     devnagrilabel  phonetics
0     NaN        NaN               NaN        NaN
1   Class      Label  Devanagari Label  Phonetics
2       0          0                 ०     Śūn'ya
3       1          1                 १        ēka
4       2          2                 २       du'ī
..    ...        ...               ...        ...
65     32  patalosaw                 स         sa
66     33         ha                 ह         ha
67     34       ksha               क्ष        kṣa
68     35        tra               त्र        tra
69     36        gya               ज्ञ        jña

[70 rows x 4 columns]

In [6]:
df.to_csv('labels.csv',index=False)

## Renaming consonants directory

In [7]:
#The consonants are present from 34-69
numconsonants=np.array(df[34:].class_) 
#numconsonants contain the number by which the file containing images of the corresponding devnagri char is sored in
print(numconsonants)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29' '30'
 '31' '32' '33' '34' '35' '36']

In [8]:
devnagriconsonants=np.array(df[34:].devnagrilabel)

In [9]:
labelconsonants =np.array(df[34:].label)
#labelconsonants give the actual name of the devnagri character 
labelconsonants

array(['ka', 'kha', 'ga', 'gha', 'kna', 'cha', 'chha', 'ja', 'jha', 'yna',
       'ta', 'tha', 'da', 'dha', 'ana', 'taa', 'thaa', 'daa', 'dhaa',
       'na', 'pa', 'pha', 'ba', 'dha', 'ma', 'ya', 'ra', 'la', 'va',
       'motosaw', 'petchiryosaw', 'patalosaw', 'ha', 'ksha', 'tra', 'gya'],
      dtype=object)

In [10]:
#As we can see 'dha' is present 2X at index 13 and 23
#AT index 23 it should be bha
labelconsonants[23]='bha'

In [11]:
#first we will change the dtype of numconsonants from object to int32
print(numconsonants.dtype)
numconsonants=numconsonants.astype('int32')
print(numconsonants.dtype)

object
int32

In [12]:
#Now we can access the labels simply by the numconsonants value
for x in numconsonants :
    print(str(x)+" "+labelconsonants[x-1])

1 ka
2 kha
3 ga
4 gha
5 kna
6 cha
7 chha
8 ja
9 jha
10 yna
11 ta
12 tha
13 da
14 dha
15 ana
16 taa
17 thaa
18 daa
19 dhaa
20 na
21 pa
22 pha
23 ba
24 bha
25 ma
26 ya
27 ra
28 la
29 va
30 motosaw
31 petchiryosaw
32 patalosaw
33 ha
34 ksha
35 tra
36 gya

In [13]:
#Now we will rename the the consonant names to their respective labels 
l1=list(map(str,range(1,37)))
consonants=os.path.join(dir,'consonants')
for x in os.listdir(consonants):
    print(x)
    if x in l1:
        print("came here")
        print(labelconsonants[int(x)-1])
        os.rename(os.path.join(consonants,x),os.path.join(consonants,labelconsonants[int(x)-1]))

tra
gha
cha
la
kna
petchiryosaw
ha
tha
va
chha
dhaa
dha
ja
thaa
ma
pa
ana
ksha
jha
patalosaw
ka
ta
ya
gya
ba
pha
ra
daa
kha
motosaw
ga
na
bha
da
yna
taa

In [14]:
df[23:33]

        class_ label devnagrilabel phonetics
23           7    ae             ए         ē
24           8    ai             ऐ        ai
25           9     o             ओ         ō
26          10    au             औ        au
27          11    an            अं        aṁ
28          12    ah            अः        aḥ
29         NaN   NaN           NaN       NaN
30         NaN   NaN           NaN       NaN
31  Consonants   NaN           NaN       NaN
32         NaN   NaN           NaN       NaN

In [15]:
#this is how we can fin out the actual devnagri char
df.loc[df.label=='tra','devnagrilabel']

68    त्र
Name: devnagrilabel, dtype: object

## Renaming vowels directory

In [16]:
df[17:29]

   class_ label devnagrilabel phonetics
17      1     a             अ         a
18      2    aa             आ         ā
19      3     i             इ         i
20      4    ee             ई         ī
21      5     u             उ         u
22      6    oo             ऊ         ū
23      7    ae             ए         ē
24      8    ai             ऐ        ai
25      9     o             ओ         ō
26     10    au             औ        au
27     11    an            अं        aṁ
28     12    ah            अः        aḥ

In [17]:
numvowels=np.array(df[17:29].class_)
labelvowels=np.array(df[17:29].label)

In [18]:
l2=list(map(str,range(1,12))) #creating a list containing 1-11 numbers
vowels=os.path.join(dir,'vowels')
for x in os.listdir(vowels):
    if x in l2:
        os.rename(os.path.join(vowels,x),os.path.join(vowels,labelvowels[int(x)-1]))